language: java

sudo: false

matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode8

script:
  - ./gradlew check jacocoCsaccessCoverageVerification

cache:
  directories:
  - ~/.gradle
